# Generated by Django 3.2.10 on 2022-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_birthdata_customer_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_male',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
