# Generated by Django 3.2.10 on 2022-06-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220612_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contain',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
