# Generated by Django 3.2.10 on 2022-03-27 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateField(verbose_name='date')),
                ('res_time', models.TimeField(null=True)),
                ('res_table_count', models.IntegerField(verbose_name='table count')),
                ('res_guest_count', models.IntegerField(verbose_name='guest count')),
                ('res_is_confermed', models.BooleanField(default=False, verbose_name='is confermed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('comment', models.CharField(max_length=500)),
                ('comm_is_shown', models.BooleanField(default=False, verbose_name='is show')),
                ('comm_sentiment', models.BooleanField(default=False, verbose_name='sentiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name')),
            ],
        ),
    ]
