# Generated by Django 3.2.10 on 2022-05-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comm_is_managed',
            field=models.BooleanField(default=False, verbose_name='managed'),
        ),
    ]
