# Generated by Django 3.2.10 on 2022-05-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_comment_comm_is_managed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='res_table_count',
        ),
    ]
